### ISSUE TITLE
404 Not Found 

### ISSUE THREAD

**Issue by noobshow** [DigitexOfficial/digitex_api_doc#7]
https://github.com/DigitexOfficial/digitex_api_doc/blob/121033388bc7850263908603564e4d31458bb04f/examples/trading_client.py#L680

**Comment by torwig** [comment]
Fixed.

**Comment by noobshow** [comment]
Hi,
Is there a restriction on how many times a API key get connected simultaneously? 

Like, I want to connect to WS for feed and another for trades...

**Comment by torwig** [comment]
Hi,
There are no restrictions on that.
You will receive the same trade messages in both connections.
And by the way for market data feed (subscriptions) you don't need to use
your API key.

Kind regards,
Yaroslav


пт, 18 вер. 2020 о 02:57 Just me <notifications@github.com> пише:

**Comment by noobshow** [comment]
Hi @torwig,
To emulate take profit and stop loss, what would be a recommended approach?

elsewhere, i would have bet it should be OCO(Order-Cancel-Order), but no mention of it in the doc...

Is [https://github.com/DigitexOfficial/digitex_api_doc/blob/9529ec1b5dc15418297394355f20f83d82991514/examples/trading_client.py#L101](url) this function what i need to know about?

**Comment by torwig** [comment]
Hi @noobshow,
To emulate take profit and stop loss orders you should use conditional orders. Function place_conditional_order() gives you the idea of doing that.
I think OCO orders are not supported on Digitex Futures Exchange.
